### ISSUE TITLE
Can't consume data from endpoint

### ISSUE THREAD

**Issue by hbelmiro** [quarkiverse/quarkus-dashbuilder#49]
I'm trying to consume data from an endpoint in my application, but I'm facing the following error:

```
Request not started, make sure that CORS is enabled.
Message: Error: java.lang.IllegalArgumentException: The data set is empty.
```

<img width="460" alt="image" src="https://github.com/quarkiverse/quarkus-dashbuilder/assets/11776454/c3d597ac-45d4-497d-97dd-d10f745ed0e2">

Both the dashboard and the endpoint are in the same Quarkus application. I'm new to Dashbuilder, so I'm probably doing something wrong, but I can't figure it out.
CORS is enabled.

Here's my dashboard: https://github.com/hbelmiro/open-social-analytics/blob/a4e7833af51f1483f3d0e4c60ee85af901ad9090/src/main/resources/dashboard.dash.yaml#L5

And here's my endpoint: https://github.com/hbelmiro/open-social-analytics/blob/a4e7833af51f1483f3d0e4c60ee85af901ad9090/src/main/java/com/thegreatapi/opensocialanalytics/GreetingResource.java

**Comment by jesuino** [comment]
Hello @hbelmiro 

Thanks for opening this issue.

You can use relative URL, the following url should work: `/hello`. Or I would also try to add `quarkus.http.cors.origins=*` to `application.properties`.

Please bear in mind that the format supported by dashbuilder is a Json 2d array, metrics or CSV.  If you want (or have to) to use other format you will have to transform using a JSONAta expression.

Please let me know if you have any question or suggestion!

**Comment by hbelmiro** [comment]
Cool @jesuino :)
It works! Thank you.
